#请填写原版名称 如果不知道请使用/PSMAD list来查看.
支持熔炼的精灵列表:
  - 喷火龙

#下面开始配置对应的熔炼反应
喷火龙:
  #最少给与点数
  基础点数: 5
  #额外的点数 属性总值*基数=额外点数综合
  ivs基数: 5
  evs基数: 5
  等级基数: 5
  稀有程度基数: 10
  #融炼完成后的指令 !ps:是由Server执行
  熔炼后的额外指令:
    - give {player} 1 64
    - give {player} 1 64
  #下面是公告的配置
  熔炼后是否全服公告:
    开关: true
    启用VV滚动: true
    公告内容: 恭喜{player}熔炼了{pokname}获得点数{pokpt}!